[server]
headless = true
fileWatcherType = "auto"
enableCORS = false
enableXsrfProtection = false

[app]
main_script = "app/app.py"

[theme]
primaryColor="#004488"
backgroundColor="#F8FAFC"
secondaryBackgroundColor="#E0F2F7"
textColor="#333333"
font="sans serif"
