SUPABASE_URL = "https://uumtdzusicvgvavlyuyc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1bXRkenVzaWN2Z3Zhdmx5dXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NDY1ODMsImV4cCI6MjA3NzMyMjU4M30.sKnbdY6g8BfCpEIkue-tt0q4KvPwQOShC3Btjak4aIM"
